### ISSUE TITLE
Property "relations" on perspective "Deployment - production" must be an array

### ISSUE THREAD

**Issue by jean** [structurizr/dsl#58]
The following DSL does not output any relations for `Deployment - production`:

```
workspace "Example" "bla bla" {
    model {
        enterprise "Ent" {
            studio = softwaresystem "Studio" "bla" {
                this_api = container "This API" "Pairing and heartbeat" "REST"
                that_api = container "That API" "" "GraphQL"
            }
            player = softwareSystem "Player" "bla bla"
        }
        google = softwareSystem "GCP" {
            firestore = container "Firestore" "" "" "Google Cloud Platform - Cloud Firestore" 
        }
        cdn = softwareSystem "CDN" "Cloudflare" 
        aws = softwareSystem "AWS" {
            redis = container "Cache" "Redis"
            postgres = container "Database" "PostgreSQL" ""
        }

        deploymentEnvironment "production" {
            deploymentNode "AWS" "" "" "Amazon Web Services - Cloud" {
                deploymentNode "US-East-1" "" "" "Amazon Web Services - Region" {
                    deploymentNode "EC2" "" "" "Amazon Web Services - EC2" {
                        this_api_instance = containerInstance this_api
                        that_api_instance = containerInstance that_api
                    }
                    deploymentNode "RDS" "" "" "Amazon Web Services - RDS PostgreSQL instance" {
                        postgres_instance = containerInstance postgres
                    }
                    deploymentNode "Redis" "" "" "Amazon Web Services - ElastiCache For Redis" {
                        redis_instance = containerInstance redis
                    }
                }
            }
        }
        that_api -> postgres "Reads and writes"
        player -> this_api "Reads and writes (pairing)"
        player -> that_api "Reads and writes (content)"
    }
    views {
        systemContext "studio" {
            include *
            autoLayout
        }
        container "studio" {
            include *
            autoLayout
        }
        container "google" {
            include *
            autoLayout
        }
        deployment studio "production" {
            include *
            autolayout lr
        }
        themes default https://static.structurizr.com/themes/amazon-web-services-2020.04.30/theme.json 
    }
}
```

Here is the generated IDL:

```
resources:

  - id: "1"
    name: "Studio"
    subtitle: "[Software System]"
    description: "bla"
    backgroundColor: "#1168bd"
    color: "#ffffff"

    children:
      - id: "2"
        name: "This API"
        subtitle: "[Container: REST]"
        description: "Pairing and heartbeat"
        backgroundColor: "#438dd5"
        color: "#ffffff"

      - id: "3"
        name: "That API"
        subtitle: "[Container: GraphQL]"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "4"
    name: "Player"
    subtitle: "[Software System]"
    description: "bla bla"
    backgroundColor: "#1168bd"
    color: "#ffffff"

  - id: "5"
    name: "GCP"
    subtitle: "[Software System]"
    backgroundColor: "#1168bd"
    color: "#ffffff"

    children:
      - id: "6"
        name: "Firestore"
        subtitle: "[Container]"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "7"
    name: "CDN"
    subtitle: "[Software System]"
    description: "Cloudflare"
    backgroundColor: "#1168bd"
    color: "#ffffff"

  - id: "8"
    name: "AWS"
    subtitle: "[Software System]"
    backgroundColor: "#1168bd"
    color: "#ffffff"

    children:
      - id: "10"
        name: "Content database"
        subtitle: "[Container]"
        description: "PostgreSQL"
        backgroundColor: "#438dd5"
        color: "#ffffff"

      - id: "9"
        name: "Cache"
        subtitle: "[Container]"
        description: "Redis"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "11"
    name: "AWS"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#232f3e"

    children:
      - id: "12"
        name: "US-East-1"
        subtitle: "[Deployment Node]"
        backgroundColor: "#ffffff"
        color: "#147eba"

        children:
          - id: "13"
            name: "EC2"
            subtitle: "[Deployment Node]"
            backgroundColor: "#ffffff"
            color: "#d86613"

            children:
              - id: "14"
                name: "This API"
                subtitle: "[Container: REST]"
                description: "Pairing and heartbeat"
                backgroundColor: "#438dd5"
                color: "#ffffff"

              - id: "15"
                name: "That API"
                subtitle: "[Container: GraphQL]"
                backgroundColor: "#438dd5"
                color: "#ffffff"

          - id: "16"
            name: "RDS"
            subtitle: "[Deployment Node]"
            backgroundColor: "#ffffff"
            color: "#3b48cc"

            children:
              - id: "17"
                name: "Content database"
                subtitle: "[Container]"
                description: "PostgreSQL"
                backgroundColor: "#438dd5"
                color: "#ffffff"

          - id: "18"
            name: "Redis"
            subtitle: "[Deployment Node]"
            backgroundColor: "#ffffff"
            color: "#3b48cc"

            children:
              - id: "19"
                name: "Cache"
                subtitle: "[Container]"
                description: "Redis"
                backgroundColor: "#438dd5"
                color: "#ffffff"

perspectives:
  - name: Static Structure
    relations:
      - from: "1"
        to: "8"
        label: "Reads and writes"

      - from: "4"
        to: "1"
        label: "Reads and writes (pairing)"

      - from: "1"
        to: "10"
        label: "Reads and writes"

      - from: "3"
        to: "10"
        label: "Reads and writes"

      - from: "3"
        to: "8"
        label: "Reads and writes"

      - from: "4"
        to: "2"
        label: "Reads and writes (pairing)"

      - from: "4"
        to: "3"
        label: "Reads and writes (content)"

  - name: Deployment - production
    relations:
```
